name: Record H2D/D2H Baselines

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  record:
    uses: google-ml-infra/bap/.github/workflows/run-benchmarks.yaml@aa854ba7bdb77966a9cc1a013417f1c1a208c4c0 # main
    with:
      registry_file: "tpu_sync/benchmarks/benchmark_registry_record.pbtxt"
      bap_ref: "aa854ba7bdb77966a9cc1a013417f1c1a208c4c0"
      runner: "linux-x86-n2-32"
